spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    username: uqi
    password: Onlinedatascientist123.
    url: jdbc:mysql://online-data-scientist.mysql.database.azure.com:3306/main
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    hikari:
#      connection-timeout: 12000
  jpa:
    hibernate:
      ddl-auto: update
#server:
#  port: 5000
#
#spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
#  datasource:
#    username: uqi
#    password: Meluqi123.
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://awseb-e-zfjukemj4x-stack-awsebrdsdatabase-8sedorozjpf5.chn4qmjggoiv.eu-central-1.rds.amazonaws.com:3306/bookPortal
#  jpa:
#    hibernate:
#      ddl-auto: update