version: "3"
services:
  be:
    image: ugurcanerdogan/online-data-scientist-be:latest
    #build: ./java
    container_name: "online-data-scientist-be"
      
  py:
    image: ugurcanerdogan/online-data-scientist-py:latest
    #build: ./python
    container_name: "online-data-scientist-py"
      
  fe:
    image: ugurcanerdogan/online-data-scientist-fe:latest
    #build: ./react
    container_name: "online-data-scientist-fe"
    depends_on:
      - be

  proxy:
    image: ugurcanerdogan/online-data-scientist-proxy:latest
    #build: ./nginx
    container_name: "online-data-scientist-proxy"
    restart: always
    ports:
      - "80:80"